### ISSUE TITLE
Firmware for ASRock A380 Low Profile

### ISSUE THREAD

**Issue by ItsR3B00T** [Solaris17/Arc-Firmware#4]
Does anyone have the firmware for this card here's the details
Vendor Id: 8086 Device Id: 56a5 SubSystem Vendor Id: 1849 SubSystem Device Id: 6006

**Comment by cryptogeek13** [comment]
May I ask why this has been closed? I have the same model and don't know how I can update the firmware. Using the files for the Asrock Challenger model doesn't work.

Unfortunately ASRock support does not want to provide those files.
